### ISSUE TITLE
a11y

### ISSUE THREAD

**Issue by zoeabryant** [redbadger/website-honestly#18]
When adding the header navigation bar we consider how to make this feature screen reader friendly. As it stands, a screen reader will read out two different navigation bars where only one might be visible.

the problem was explained on #dx channel

> We have desktop navbar and mobile navigation which are visible or hidden depending on the screen size. They also have slightly different items for mobile and desktop navs. From a11y perspective we are wondering what we should do. Should we pick one of the navbars and put `aria-hidden` on the other one? Should we use clientside javascript and mimic media queries by applying `aria-hidden` to different navbars depending on the screensize? What is the best practice?
> According to the standards we can’t just pick one nav bar to be hidden or the other - https://www.w3.org/TR/wai-aria/states_and_properties#aria-hidden `aria-hidden` needs to be actually indicative of the state. This is particularly important in the case of partially sighted users.

We might need to add client side JS to cater for this

**Comment by zoeabryant** [comment]
# A11y fixes for Honestly

using Voice Over (VO tools) on mac:
press `cmd F5` to activate voiceover
`VO-` means ctrl alt (the voice over command shortcut)

acceptance criteria -
  `VO-U`, the list of all links on the page, should be logical
  `VO-I`, the list of items on the page, should be logical
  You should be able to logically navigate through with the `tab` key

cross devices to consider - 
  something else? windows?
  iOS?
  Android?

immediate problems:
hopefully fixable by aria-hidden in some cases: https://www.w3.org/TR/wai-aria/states_and_properties#aria-hidden

- [ ] header nav bar
   - `VO-U` can access the hidden checkbox for the mobile menu
   - `VO-U` make sure we're only displaying one group of nav links
   - When tabbing it goes into mobile navbar even when it is hidden

- [ ] svgs
   - `VO-U` title of the red badger logo

- [ ] Case studies section
   - `VO-U` titles of the case studies section on the homepage are unhelpful
   - `VO-U` features 3 separate links for each case study

- [ ] footer
   - `VO-U` remove the footer nav links, it repeats the menu nav links
   - `VO-U` google maps link is repeated
   - `VO-U` title of the footer social media links are unhelpful

**Comment by asavin** [comment]
Going to ignore the Red Badger logo SVG issue for now, since it is going to be replaced.

**Comment by zoeabryant** [comment]
- REJECTED: VO-U remove the footer nav links, it repeats the menu nav links
if element is visible, we should read it out, however much the repetition is tedious.
- DISCUSS: VO-U google maps link is repeated
It might make more sense to say `Old Street` and `Old Street station` on the SVG map, as the screenreader doesn't know one of the `Old Street` texts indicates a station
- DONE: #113 VO-U title of the footer social media links are unhelpful

**Comment by zoeabryant** [comment]
Acceptance criteria documentation so far:

## Listen to on screenreaders

#### What we are looking for
When using `VO-U`, `VO-I` the content should be logical

#### Tips
* use fangs plugin
* use role attribute
* use title attribute
* use hidden attribute

## Navigate keyboard only

#### What we are looking for
Using `tab` (forwards) and `shift tab`(backwards) you should be able to use all the interactive elements of the site

#### Tips
* use tabindex
* use enter key, space bar to submit forms

**Comment by gregdorward** [comment]
This one is still an issue, and Zoe's comments on October 27th best summarise the current state of play

**Comment by dpiatek** [comment]
Closing, will migrate the recommendations from @zoeabryant to a new a11y card
